name: CLI - Publish to NPM

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run (will not actually publish)'
        type: boolean
        required: false
        default: false
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          cd apps/cli
          pnpm install
      - uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./apps/cli/package.json
          dry-run: ${{ inputs.dry-run }}
