name: CLI - Publish to NPM

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run (will not actually publish)'
        type: boolean
        required: false
        default: false
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          cd apps/cli
          pnpm install
      - name: Publish CLI package
        run: |
          cd apps/cli
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            echo "Dry run mode - would publish package"
            pnpm publish --dry-run --no-git-checks
          else
            pnpm publish --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
